apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k8s-native-local-env
build:
  artifacts:
  - image: registry.rancher.localhost/album-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k3s.yaml
